=== cheeseonamonkey/Iambic.cc/data/poems.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://iambic.cc/data/poems.schema.json",
  "title": "Iambic demo poem library",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["content", "title", "author", "url"],
    "properties": {
      "content": {"type": "string", "minLength": 1},
      "title": {"type": "string", "minLength": 1},
      "author": {"type": "string", "minLength": 1},
      "url": {"type": "string"}
    },
    "additionalProperties": false
  }
}

=== cheeseonamonkey/Iambic.cc/data/poems.json
[
  {
    "title": "Autumn Referendum",
    "author": "cheeseonamonkey",
    "content": "[Each] [leaf] [casts] <its> [vote]\n<The> [Au]<tumn> [Ref]<er><en>[dum]\n[Na]<tions> [live] <or> [die].",
    "url": ""
  },
  {
    "title": "Sonnet 18",
    "author": "William Shakespeare",
    "content": "<Shall> [I] <com>[pare] <thee> [to] <a> [sum]<mer’s> [day]?\n<Thou> [art] <more> [love]<ly> [and] <more> [tem]<perate>;\n[Rough] [winds] <do> [shake] <the> [dar]<ling> [buds] <of> [May],\n<And> [sum]<mer’s> [lease] <hath> [all] <too> [short] <a> [date];\n[Some]<time> <too> [hot] <the> [eye] <of> [heav]<en> [shines],\n<And> [oft]<en> [is] <his> [gold] <com>[plex]<ion> [dimm’d];\n<And> [ev]<ery> [fair] <from> [fair] <some>[time] <de>[clines],\n<By> [chance] <or> [na]<ture’s> [chang]<ing> [course] <un>[trimm’d];",
    "url": "https://www.poetryfoundation.org/poems/45087/sonnet-18-shall-i-compare-thee-to-a-summers-day"
  },
  {
    "title": "Anecdote",
    "author": "Dorothy Parker",
    "content": "<So> [si]<lent> [I] <when> [Love] <was> [by]\n<He> [yawned], <and> [turned] <a>[way];\n<But> [Sorr]<ow> [clings] <to> <my> [apr]<on>-[strings],\n<I> [have] <so> [much] <to> [say].",
    "url": "https://www.gutenberg.org/ebooks/68353"
  },
  {
    "title": "One Perfect Rose",
    "author": "Dorothy Parker",
    "content": "<A> [sin]<gle> [flow’r] <he> [sent] <me> [since] <we> [met].\n<All> [ten]<der><ly> [his] <mess>[en]<ger> [he] <chose>;\n[Deep]-[heart]<ed>, [pure], <with> [scent]<ed> [dew] <still> [wet]—\n<One> [per]<fect> [rose].\n\n<I> [knew] <the> [lan]<guage> <of> [the] <flow>[er]<et>;\n<My> [frag]<ile> [leaves], <it> [said], <his> [heart] <en>[close].\n<Love> [long] <has> [tak]<en> [for] <his> [am]<u>[let]\n<One> [per]<fect> [rose].\n\n<Why> [is] <it> [no] <one> [ev]<er> [sent] <me> [yet]\n<One> [per]<fect> [lim]<ou>[sine], <do> [you] <sup>[pose]?\n<Ah> [no], <it’s> [al]<ways> [just] <my> [luck] <to> [get]\n<One> [per]<fect> [rose].",
    "url": "https://www.gutenberg.org/ebooks/68353"
  },
  {
    "title": "The Conqueror Worm",
    "author": "Edgar Allan Poe",
    "content": "[Lo]! <’tis> <a> [ga]<la> [night]\n<With>[in] <the> [lone]<some> [lat]<ter> [years]!\n<An> [an]<gel> [throng], <be>[winged], <be>[dight]\n<In> [veils], <and> [drowned] <in> [tears],\n[Sit] <in> <a> [the]<a>[tre], <to> [see]\n<A> [play] <of> [hopes] <and> [fears],\n<While> <the> [or]<ches>[tra] [breathes] <fit><ful>[ly]\n<The> [mu]<sic> <of> <the> [spheres].",
    "url": "https://www.gutenberg.org/ebooks/76996"
  },
  {
    "title": "A Dream Within a Dream",
    "author": "Edgar Allan Poe",
    "content": "[Take] <this> [kiss] <up>[on] <the> [brow]!\n[And], <in> [part]<ing> [from] <you> [now],\n[Thus] <much> [let] <me> <a>[vow]—\n[You] <are> <not> [wrong], <who> [deem]\n[That] <my> [days] <have> [been] <a> [dream]:\n[Yet] <if> [hope] <has> [flown] <a>[way]\n<In> <a> [night], <or> <in> <a> [day],\n<In> <a> [vi]<sion>, <or> <in> [none],\n[Is] <it> [there]<fore> <the> [less] [gone]?\n[All] <that> <we> [see] <or> [seem]\n[Is] <but> <a> [dream] <with>[in] <a> [dream].",
    "url": "https://www.gutenberg.org/ebooks/76996"
  },
  {
    "title": "Jabberwocky",
    "author": "Lewis Carroll",
    "content": "<’Twas> [bril]<lig>, <and> <the> [sli]<thy> [toves]\n<Did> [gyre] <and> [gim]<ble> <in> <the> [wabe];\n<All> [mim]<sy> [were] <the> [bor]<o>[goves],\n<And> <the> [mome] <raths> <out>[grabe].",
    "url": "https://www.poetryfoundation.org/poems/42916/jabberwocky"
  },
  {
    "title": "Psalm 139:1–6 (KJV)",
    "author": "David",
    "content": "<O> [LORD], <thou> <hast> [searched] <me>, <and> [known] <me>.\n<Thou> [know]<est> <my> [down][sit]<ting> <and> <mine> [up][ris]<ing>, <thou> <un><der>[stand]<est> <my> [thought] <a>[far] [off].\n<Thou> [com]<pass><est> <my> [path] <and> <my> [ly]<ing> [down], <and> <art> <ac>[quaint]<ed> <with> [all] <my> [ways].\n<For> <there> <is> [not] <a> [word] <in> <my> [tongue], <but>, [lo], <O> [LORD], <thou> [know]<est> <it> <al><to>[geth]<er>.\n<Thou> <hast> <be>[set] <me> <be>[hind] <and> <be>[fore], <and> [laid] <thine> [hand] <up>[on] <me>.\n[Such] [know]<ledge> <is> <too> [won]<der><ful> <for> <me>; <it> <is> [high], <I> [can]<not> <at>[tain] [un]<to> <it>.",
    "url": "https://www.biblegateway.com/passage/?search=Psalm%20139%3A1-6&version=KJV"
  }
]
